branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/git"
  
git:
  assets:
    - package.json
    - package-lock.json   # Add other files if needed, such as `yarn.lock`
  message: "chore(release): ${nextRelease.version} [skip ci]"   # Avoid triggering CI on the release commit
