name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js 20
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Install Semantic Release and its plugins
      - name: Install Semantic Release
        run: |
          bun add --dev semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github

      # Run Semantic Release
      - name: Run Semantic Release
        id: semantic-release
        run: |
          npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # Fetch the latest release tag
      - name: Get Latest Release Tag
        id: get_tag
        run: echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      # Pull Vercel environment information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Build the project with the tag name
      - name: Build Project
        run: vercel build --prod --meta version=${{ env.TAG }} --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy to Vercel using the tag
      - name: Deploy Project
        run: vercel deploy --prebuilt --prod --meta version=${{ env.TAG }} --token=${{ secrets.VERCEL_TOKEN }}
